server:
  port: 8082

spring:
  application:
    name: carrito-service

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:camisetas360}
    password: ${RABBITMQ_PASSWORD:camisetas360_dev}
    virtual-host: ${RABBITMQ_VHOST:/camisetas360}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ENTRA_ISSUER_URI:https://login.microsoftonline.com/e5372bf0-c5e3-4286-887c-79069f209c1f/v2.0}
          audiences:
            - ${ENTRA_AUDIENCE:719c999d-0f57-4ad5-9bd9-a72be5ca07e0}
