CREATE TABLE checkout_requests (
    id UUID PRIMARY KEY,
    user_email VARCHAR(255) NOT NULL,
    total_amount DOUBLE PRECISION NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status = 'PROCESSING'),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE checkout_request_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkout_id UUID NOT NULL REFERENCES checkout_requests(id),
    sku VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price DOUBLE PRECISION NOT NULL CHECK (unit_price > 0)
);

CREATE INDEX ix_checkout_request_items_checkout ON checkout_request_items(checkout_id);
