CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(255),
    name VARCHAR(255),
    category VARCHAR(255),
    price DOUBLE PRECISION,
    stock INTEGER,
    description VARCHAR(255)
);
