server:
  port: 8083

spring:
  application:
    name: auth-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/e5372bf0-c5e3-4286-887c-79069f209c1f/v2.0
          audiences:
            - 719c999d-0f57-4ad5-9bd9-a72be5ca07e0

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never
