CREATE TABLE email_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender TEXT NOT NULL,
    recipient TEXT NOT NULL,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    sent_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX ix_email_deliveries_recipient_sent_at ON email_deliveries(recipient, sent_at DESC);
